## Homework

> Note: sometimes your answer doesn't match one of the options exactly. 
> That's fine. 
> Select the option that's closest to your solution.


### Dataset

In this homework, we will use the lead scoring dataset Bank Marketing dataset. Download it from [here](https://raw.githubusercontent.com/alexeygrigorev/datasets/master/course_lead_scoring.csv).

Or you can do it with `wget`:

```bash
wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/course_lead_scoring.csv
```

In this dataset our desired target for classification task will be `converted` variable - has the client signed up to the platform or not. 

### Data preparation

* Check if the missing values are presented in the features.
* If there are missing values:
    * For caterogiral features, replace them with 'NA'
    * For numerical features, replace with with 0.0

In [1]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/course_lead_scoring.csv

--2025-10-13 08:22:21--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/course_lead_scoring.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8002::154, 2606:50c0:8001::154, 2606:50c0:8000::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8002::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 80876 (79K) [text/plain]
Saving to: ‘course_lead_scoring.csv’

course_lead_scoring 100%[===================>]  78.98K  --.-KB/s    in 0.04s

2025-10-13 08:22:22 (1.85 MB/s) - ‘course_lead_scoring.csv’ saved [80876/80876]

In [109]:
import numpy as np
import pandas as pd

In [110]:
df = pd.read_csv('course_lead_scoring.csv')

In [111]:
df.head()

,lead_source,industry,number_of_courses_viewed,annual_income,employment_status,location,interaction_count,lead_score,converted
0,paid_ads,NaN,1,79450.0,unemployed,south_america,4,0.94,1
1,social_media,retail,1,46992.0,employed,south_america,1,0.80,0
2,events,healthcare,5,78796.0,unemployed,australia,3,0.69,1
3,paid_ads,retail,2,83843.0,NaN,australia,1,0.87,0
4,referral,education,3,85012.0,self_employed,europe,3,0.62,1

In [112]:
df.dtypes

lead_source                  object
industry                     object
number_of_courses_viewed      int64
annual_income               float64
employment_status            object
location                     object
interaction_count             int64
lead_score                  float64
converted                     int64
dtype: object

In [113]:
categorical = [c for c in df.columns if df[c].dtype == 'object']
categorical

['lead_source', 'industry', 'employment_status', 'location']

In [114]:
numerical = [c for c in df.columns if df[c].dtype != 'object']
numerical

['number_of_courses_viewed',
 'annual_income',
 'interaction_count',
 'lead_score',
 'converted']

In [115]:
df.isnull().sum()

lead_source                 128
industry                    134
number_of_courses_viewed      0
annual_income               181
employment_status           100
location                     63
interaction_count             0
lead_score                    0
converted                     0
dtype: int64

In [116]:
df[categorical] = df[categorical].fillna('NA')

In [117]:
df.isnull().sum()

lead_source                   0
industry                      0
number_of_courses_viewed      0
annual_income               181
employment_status             0
location                      0
interaction_count             0
lead_score                    0
converted                     0
dtype: int64

In [118]:
df[numerical] = df[numerical].fillna(0.0)

In [119]:
df.isnull().sum()

lead_source                 0
industry                    0
number_of_courses_viewed    0
annual_income               0
employment_status           0
location                    0
interaction_count           0
lead_score                  0
converted                   0
dtype: int64

### Question 1

What is the most frequent observation (mode) for the column `industry`?

- `NA`
- `technology`
- `healthcare`
- `retail`

In [120]:
df['industry'].mode()

0    retail
Name: industry, dtype: object

In [121]:
df['industry'].value_counts()

industry
retail           203
finance          200
other            198
healthcare       187
education        187
technology       179
manufacturing    174
NA               134
Name: count, dtype: int64

ans: retail

### Question 2

Create the [correlation matrix](https://www.google.com/search?q=correlation+matrix) for the numerical features of your dataset. 
In a correlation matrix, you compute the correlation coefficient between every pair of features.

What are the two features that have the biggest correlation?

- `interaction_count` and `lead_score`
- `number_of_courses_viewed` and `lead_score`
- `number_of_courses_viewed` and `interaction_count`
- `annual_income` and `interaction_count`

Only consider the pairs above when answering this question.

In [122]:
import seaborn as sns
import matplotlib.pyplot as plt

In [123]:
corr = df[numerical].corr()

In [124]:
corr

,number_of_courses_viewed,annual_income,interaction_count,lead_score,converted
number_of_courses_viewed,1.000000,0.009770,-0.023565,-0.004879,0.435914
annual_income,0.009770,1.000000,0.027036,0.015610,0.053131
interaction_count,-0.023565,0.027036,1.000000,0.009888,0.374573
lead_score,-0.004879,0.015610,0.009888,1.000000,0.193673
converted,0.435914,0.053131,0.374573,0.193673,1.000000

ans: annual_income and interaction_count

### Split the data

* Split your data in train/val/test sets with 60%/20%/20% distribution.
* Use Scikit-Learn for that (the `train_test_split` function) and set the seed to `42`.
* Make sure that the target value `y` is not in your dataframe.

In [125]:
from sklearn.model_selection import train_test_split

In [126]:
df_train_full, df_test, y_train_full, y_test = train_test_split(df, df['converted'].values, test_size=0.2, random_state=42)

In [127]:
y_train_full

array([0, 1, 1, ..., 0, 1, 0], shape=(1169,))

In [128]:
df_train, df_val, y_train, y_val = train_test_split(df_train_full, y_train_full, test_size=0.25, random_state=42)

In [129]:
len(df_train), len(y_train), len(df_val), len(y_val)

(876, 876, 293, 293)

In [130]:
del df_train_full['converted']
del df_train['converted']
del df_val['converted']

In [131]:
df_train.head()

,lead_source,industry,number_of_courses_viewed,annual_income,employment_status,location,interaction_count,lead_score
1077,paid_ads,retail,0,58472.0,student,middle_east,5,0.03
463,organic_search,manufacturing,3,71738.0,student,middle_east,6,0.77
842,paid_ads,technology,3,81973.0,employed,north_america,2,0.59
835,NA,technology,1,74956.0,employed,europe,3,0.34
837,organic_search,retail,3,59335.0,student,australia,1,0.98

### Question 3

* Calculate the mutual information score between `y` and other categorical variables in the dataset. Use the training set only.
* Round the scores to 2 decimals using `round(score, 2)`.

Which of these variables has the biggest mutual information score?
  
- `industry`
- `location`
- `lead_source`
- `employment_status`

In [132]:
from sklearn.metrics import mutual_info_score

In [133]:
def mutual_info_convert_score(series):
    return mutual_info_score(series, y_train)

In [134]:
mi = df_train[categorical].apply(mutual_info_convert_score)
mi.sort_values(ascending=False)

lead_source          0.035396
employment_status    0.012938
industry             0.011575
location             0.004464
dtype: float64

ans: lead_source

### Question 4

* Now let's train a logistic regression.
* Remember that we have several categorical variables in the dataset. Include them using one-hot encoding.
* Fit the model on the training dataset.
    - To make sure the results are reproducible across different versions of Scikit-Learn, fit the model with these parameters:
    - `model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)`
* Calculate the accuracy on the validation dataset and round it to 2 decimal digits.

What accuracy did you get?

- 0.64
- 0.74
- 0.84
- 0.94

In [135]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction import DictVectorizer
from sklearn.metrics import accuracy_score

In [139]:
numerical

['number_of_courses_viewed',
 'annual_income',
 'interaction_count',
 'lead_score',
 'converted']

In [140]:
numerical = [c for c in numerical if c != 'converted']

In [141]:
dv = DictVectorizer(sparse=False)

train_dict = df_train[numerical + categorical].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

val_dict = df_val[numerical + categorical].to_dict(orient='records')
X_val = dv.transform(val_dict)

In [142]:
model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)

In [143]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [144]:
y_pred = model.predict_proba(X_val)[:, 1]

In [145]:
converted_decision = (y_pred >= 0.5)

In [147]:
(y_val == converted_decision).mean()

np.float64(0.6996587030716723)

In [148]:
accuracy_score(y_val, (y_pred >= 0.5))

0.6996587030716723

In [149]:
y_pred_2 = model.predict(X_val)

In [150]:
original_acc = accuracy_score(y_val, y_pred_2)
original_acc

0.6996587030716723

In [76]:
round((y_val == converted_decision).mean(), 2)

np.float64(0.7)

ans: the closest answer is 0.74

### Question 5 

* Let's find the least useful feature using the *feature elimination* technique.
* Train a model using the same features and parameters as in Q4 (without rounding).
* Now exclude each feature from this set and train a model without it. Record the accuracy for each model.
* For each feature, calculate the difference between the original accuracy and the accuracy without the feature. 

Which of following feature has the smallest difference?

- `'industry'`
- `'employment_status'`
- `'lead_score'`

> **Note**: The difference doesn't have to be positive.

In [89]:
df_train

,lead_source,industry,number_of_courses_viewed,annual_income,employment_status,location,interaction_count,lead_score
1077,paid_ads,retail,0,58472.0,student,middle_east,5,0.03
463,organic_search,manufacturing,3,71738.0,student,middle_east,6,0.77
842,paid_ads,technology,3,81973.0,employed,north_america,2,0.59
835,NA,technology,1,74956.0,employed,europe,3,0.34
837,organic_search,retail,3,59335.0,student,australia,1,0.98
...,...,...,...,...,...,...,...,...
725,organic_search,other,1,43907.0,employed,australia,4,0.33
401,social_media,retail,3,64969.0,employed,north_america,1,0.18
957,NA,education,3,89042.0,employed,asia,4,0.75
992,social_media,manufacturing,1,0.0,self_employed,europe,1,0.65
1267,events,finance,4,50259.0,student,asia,3,0.54

In [91]:
df

,lead_source,industry,number_of_courses_viewed,annual_income,employment_status,location,interaction_count,lead_score,converted
0,paid_ads,NA,1,79450.0,unemployed,south_america,4,0.94,1
1,social_media,retail,1,46992.0,employed,south_america,1,0.80,0
2,events,healthcare,5,78796.0,unemployed,australia,3,0.69,1
3,paid_ads,retail,2,83843.0,NA,australia,1,0.87,0
4,referral,education,3,85012.0,self_employed,europe,3,0.62,1
...,...,...,...,...,...,...,...,...,...
1457,referral,manufacturing,1,0.0,self_employed,north_america,4,0.53,1
1458,referral,technology,3,65259.0,student,europe,2,0.24,1
1459,paid_ads,technology,1,45688.0,student,north_america,3,0.02,1
1460,referral,NA,5,71016.0,self_employed,north_america,0,0.25,1
1461,organic_search,finance,3,92855.0,student,north_america,3,0.41,1

In [96]:
all_features = list(df_train.columns)

for x in all_features:
    included_features = [f for f in all_features if f != x]
    model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
    
    dv = DictVectorizer(sparse=False)
    
    train_dict = df_train[included_features].to_dict(orient='records')
    X_train = dv.fit_transform(train_dict)
    val_dict = df_val[included_features].to_dict(orient='records')
    X_val = dv.transform(val_dict)


    
    model.fit(X_train, y_train)
    y_pred = model.predict(X_val)
    acc_score = accuracy_score(y_val, y_pred)
    diff = abs(original_acc - acc_score)
    print(f'feature: {x:<20} ---> diff: {diff:.4f}')
    print()

feature: lead_source          ---> diff: 0.0034

feature: industry             ---> diff: 0.0000

feature: number_of_courses_viewed ---> diff: 0.1433

feature: annual_income        ---> diff: 0.1536

feature: employment_status    ---> diff: 0.0034

feature: location             ---> diff: 0.0102

feature: interaction_count    ---> diff: 0.1433

feature: lead_score           ---> diff: 0.0068

In [97]:
all_features = list(df_train.columns)

for x in all_features:
    included_features = [f for f in all_features if f != x]
    model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
    
    dv = DictVectorizer(sparse=False)
    
    train_dict = df_train[included_features].to_dict(orient='records')
    X_train = dv.fit_transform(train_dict)
    val_dict = df_val[included_features].to_dict(orient='records')
    X_val = dv.transform(val_dict)


    
    model.fit(X_train, y_train)
    y_pred = (model.predict_proba(X_val)[:, 1] >= 0.5)
    acc_score = accuracy_score(y_val, y_pred)
    diff = abs(original_acc - acc_score)
    print(f'feature: {x:<20} ---> diff: {diff:.4f}')
    print()

feature: lead_source          ---> diff: 0.0034

feature: industry             ---> diff: 0.0000

feature: number_of_courses_viewed ---> diff: 0.1433

feature: annual_income        ---> diff: 0.1536

feature: employment_status    ---> diff: 0.0034

feature: location             ---> diff: 0.0102

feature: interaction_count    ---> diff: 0.1433

feature: lead_score           ---> diff: 0.0068

ans: the feature that least affects the accuracy is industry

### Question 6

* Now let's train a regularized logistic regression.
* Let's try the following values of the parameter `C`: `[0.01, 0.1, 1, 10, 100]`.
* Train models using all the features as in Q4.
* Calculate the accuracy on the validation dataset and round it to 3 decimal digits.

Which of these `C` leads to the best accuracy on the validation set?

- 0.01
- 0.1
- 1
- 10
- 100

In [101]:
dv = DictVectorizer(sparse=False)
dicts_train = df_train.to_dict(orient='records')
dicts_val = df_val.to_dict(orient='records')
X_train = dv.fit_transform(dicts_train)
X_val = dv.transform(dicts_val)

In [108]:
for C in [0.01, 0.1, 1, 10, 100]:
    model = LogisticRegression(solver='liblinear', C=C, max_iter=1000, random_state=42)
    model.fit(X_train, y_train)
    y_pred = model.predict_proba(X_val)[:, 1]
    acc_score = accuracy_score(y_val, (y_pred >= 0.5))
    print(f'C: {C:<10} ---> accuracy: {acc_score:.3f}')

C: 0.01       ---> accuracy: 0.700
C: 0.1        ---> accuracy: 0.700
C: 1          ---> accuracy: 0.700
C: 10         ---> accuracy: 0.700
C: 100        ---> accuracy: 0.700

ans:  all the C values gave identical accuracy on the validation set, so the answer is 0.01 because it is the smallest